### ISSUE TITLE
edge case when doing stralloc_readyplus

### ISSUE THREAD

**Issue by magenbluten** [skarnet/skalibs#2]
`sa->len + n` might wrap arround ( in case of user controlled `n` ). leaving the "buffer" in a state where `len` points past `sa->s + sa->a` because in `stralloc_ready_tuned` the condition `sa->len < n` is not verified/checked. or am i dreaming?

- https://github.com/skarnet/skalibs/blob/8c16e68dda72032e81a624360b1abb1006e33481/src/include/skalibs/stralloc.h#L22
- https://github.com/skarnet/skalibs/blob/8c16e68dda72032e81a624360b1abb1006e33481/src/libstddjb/stralloc_ready_tuned.c#L8

**Comment by skarnet** [comment]
You're right. Good catch! Thanks, will fix.
