### ISSUE TITLE
wrong version number in package/info

### ISSUE THREAD

**Issue by tseeling** [skarnet/skalibs#4]
for tag 2.12.0.1 the info file contains version number 2.12.1.0
with --enable-slashpackage will install to wrong directory

**Comment by skarnet** [comment]
The head of the `master` branch is generally ahead of the latest numbered version, so it's possible that its version doesn't match the previous tag.

You can check that the [`package/info`](https://github.com/skarnet/skalibs/blob/v2.12.0.1/package/info) file of the `v2.12.0.1` tag checkout is the correct one.

Don't build from the master HEAD if you don't want to live on the bleeding edge. 😉

**Comment by skarnet** [comment]
Closing this :-)
